# Generated by Django 2.0.1 on 2018-02-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
